version: '3'

networks:
  frontend:
  backend:

volumes:
  vol-mw:
  vol-mw-db:

services:
  traefik:
    image: traefik:latest
    command: --api --docker --acme.email="${ACME_EMAIL}"
    restart: always
    networks: 
      - backend
      - frontend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    ports:
      - "80:80"
      - "443:443"
    labels:
            - "traefik.docker.network=frontend"
            - "traefik.enable=true"
            - "traefik.frontend.rule=Host:${TRAEFIK_DOMAINS}; PathPrefixStrip:/traefik"
            - "traefik.port=8080"
            - "traefik.protocol=http"
            - "traefik.frontend.auth.basic=${BASIC_AUTH}"
  watchtower:
   # https://hub.docker.com/r/centurylink/watchtower/
    image: v2tec/watchtower:latest
    # https://github.com/v2tec/watchtower#options
    # This schedule applies updates (if available) at midnight.
    command: --cleanup --schedule "0 0 0 * * *"
    restart: always
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  database:
    image: mariadb:10.3
    restart: always
    networks:
      - backend
    volumes:
      - vol-mw-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MW_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MW_DB_NAME}
      MYSQL_USER: ${MW_DB_USER}
      MYSQL_PASSWORD: ${MW_DB_PASSWORD}
 
  mw:
    image: mediawiki:latest
    depends_on:
      - database
    links:
      - database
    restart: always
    networks:
      - backend
      - frontend
    expose:
      - "80"
    volumes:
      - vol-mw:/var/www/html/
      - ./php.ini:/usr/local/etc/php/php.ini
#	Uncomment the below line once LocalSettings has been placed in /root/compose/!   
#      - ./LocalSettings.php:/var/www/html/LocalSettings.php
    environment:
      MW_DB_HOST: compose_database_1:3306
      MYSQL_DATABASE: ${MW_DB_NAME}
      MYSQL_USER: ${MW_DB_USER}
      MYSQL_PASSWORD: ${MW_DB_PASSWORD}
    labels:
      - "traefik.docker.network=frontend"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:${MW_DOMAINS}"
      - "traefik.port=80"
      - "traefik.protocol=http"
